import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '../app/StyledComponentsRegistry';
import Header from '../components/Header';
import store from '../redux/store';
import { Provider } from 'react-redux';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // <Provider store={store}>
    <StyledComponentsRegistry>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
            rel="stylesheet"
          />
          <Header></Header>
          {children}
        </body>
      </html>
    </StyledComponentsRegistry>
    // </Provider>
  );
}
